"""answers: add composite index

Revision ID: d4a67898a580
Revises: 02362b9d60b4
Create Date: 2025-08-30 16:02:17.139563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a67898a580'
down_revision: Union[str, Sequence[str], None] = '02362b9d60b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_answer_question_user', 'answers', ['question_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_answer_question_user', table_name='answers')
    # ### end Alembic commands ###
